{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark.serviceAccountName" . }}
  labels:
{{ include "spark.labels" . | nindent 4 }}
{{- end -}}
