apiVersion: v1
kind: Service
metadata:
    name: {{ include "spark.fullname" . }}
    labels:
        {{- include "spark.labels" . | nindent 4 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          targetPort: http
          protocol: TCP
          name: http
        - port: {{ .Values.service.grpcPort }}
          targetPort: grpc
          protocol: TCP
          name: grpc
    selector:
        {{- include "spark.selectorLabels" . | nindent 4 }}
