{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "user.serviceAccountName" . }}
  labels:
{{ include "user.labels" . | nindent 4 }}
{{- end -}}
